language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt
script:
  # - python makeserver.py -v release -e y -l y -m 4G --network 50 -s 0 -o y
  - PyInstaller makeserver.py --noconfirm --icon=icon.ico --name="mc-server-script" --onefile